// Static categories for diamond shapes
const DIAMOND_CATEGORIES = [
  { _id: "round", name: "Round" },
  { _id: "oval", name: "Oval" },
  { _id: "pear", name: "Pear" },
  { _id: "emerald", name: "Emerald" },
  { _id: "sq_emerald", name: "Sq. Emerald" },
  { _id: "cushion_brilliant", name: "Cushion Brilliant" },
  { _id: "cushion_modified", name: "Cushion Modified" },
  { _id: "crisscut", name: "Crisscut" },
  { _id: "marquise", name: "Marquise" },
  { _id: "radiant", name: "Radiant" },
  { _id: "sq_radiant", name: "Sq. Radiant" },
  { _id: "princess", name: "Princess" },
  { _id: "asscher", name: "Asscher" },
  { _id: "heart", name: "Heart" },
  { _id: "old_miner", name: "Old Miner" },
  { _id: "european_cut", name: "European Cut" },
  { _id: "octagonal", name: "Octagonal" },
  { _id: "pentagonal", name: "Pentagonal" },
  { _id: "hexagonal", name: "Hexagonal" },
  { _id: "trapzoid", name: "Trapzoid" },
  { _id: "traingular", name: "Traingular" },
  { _id: "trilliant", name: "Trilliant" },
  { _id: "lozenge", name: "Lozenge" },
  { _id: "kite", name: "Kite" },
  { _id: "baguette", name: "Baguette" },
  { _id: "shield", name: "Shield" },
  { _id: "butterfly", name: "Butterfly" },
  { _id: "half_moon", name: "Half Moon" },
  { _id: "rose_cut", name: "Rose Cut" },
];

export { DIAMOND_CATEGORIES };
