// Static categories for diamond shapes
const DIAMOND_CATEGORIES = [
  { _id: "round", name: "Round", image: "round.webp" },
  { _id: "oval", name: "Oval", image: "oval.webp" },
  { _id: "pear", name: "Pear", image: "pear.webp" },
  { _id: "emerald", name: "Emerald", image: "emerald.webp" },
  { _id: "sq_emerald", name: "Sq. Emerald", image: "sq_emerald.webp" },
  {
    _id: "cushion_brilliant",
    name: "Cushion Brilliant",
    image: "cushion_brilliant.webp",
  },
  {
    _id: "cushion_modified",
    name: "Cushion Modified",
    image: "cushion_modified.webp",
  },
  { _id: "crisscut", name: "Crisscut", image: "crisscut.webp" },
  { _id: "marquise", name: "Marquise", image: "marquise.webp" },
  { _id: "radiant", name: "Radiant", image: "radiant.webp" },
  { _id: "sq_radiant", name: "Sq. Radiant", image: "sq_radiant.webp" },
  { _id: "princess", name: "Princess", image: "princess.webp" },
  { _id: "asscher", name: "Asscher", image: "asscher.webp" },
  { _id: "heart", name: "Heart", image: "heart.webp" },
  { _id: "old_miner", name: "Old Miner", image: "old_miner.webp" },
  { _id: "european_cut", name: "European Cut", image: "european_cut.webp" },
  { _id: "octagonal", name: "Octagonal", image: "octagonal.webp" },
  { _id: "pentagonal", name: "Pentagonal", image: "pentagonal.webp" },
  { _id: "hexagonal", name: "Hexagonal", image: "hexagonal.webp" },
  { _id: "trapzoid", name: "Trapzoid", image: "trapzoid.webp" },
  { _id: "triangular", name: "Triangular", image: "triangular.webp" },
  { _id: "trilliant", name: "Trilliant", image: "trilliant.webp" },
  { _id: "lozenge", name: "Lozenge", image: "lozenge.webp" },
  { _id: "kite", name: "Kite", image: "kite.webp" },
  { _id: "baguette", name: "Baguette", image: "baguette.webp" },
  { _id: "shield", name: "Shield", image: "shield.webp" },
  { _id: "butterfly", name: "Butterfly", image: "butterfly.webp" },
  { _id: "half_moon", name: "Half Moon", image: "half_moon.webp" },
  { _id: "rose_cut", name: "Rose Cut", image: "rose_cut.webp" },
  // Adding missing shapes from the list
  { _id: "cushion", name: "Cushion", image: "cushion.webp" },
  {
    _id: "tapered_baguette",
    name: "Tapered Baguette",
    image: "tapered_baguette.webp",
  },
  { _id: "bullet", name: "Bullet", image: "bullet.webp" },
  { _id: "briolette", name: "Briolette", image: "briolette.webp" },
  { _id: "calf", name: "Calf", image: "calf.webp" },
];

export { DIAMOND_CATEGORIES };
